In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
import pandas as pd

In [3]:
CSV_COLUMN_NAMES = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth', 'species']
SPECIES = ['Setosa', 'Versicolor', 'Virginica']
train_path = tf.keras.utils.get_file('iris_training.csv', "https://storage.googleapis.com/download.tensorflow.org/data/iris_training.csv")
test_path = tf.keras.utils.get_file('iris_test.csv', "https://storage.googleapis.com/download.tensorflow.org/data/iris_test.csv")
train = pd.read_csv(train_path, names=CSV_COLUMN_NAMES, header=0)
test = pd.read_csv(test_path, names=CSV_COLUMN_NAMES, header=0)

In [4]:
train.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth  species
0          6.4         2.8          5.6         2.2        2
1          5.0         2.3          3.3         1.0        1
2          4.9         2.5          4.5         1.7        2
3          4.9         3.1          1.5         0.1        0
4          5.7         3.8          1.7         0.3        0

In [6]:
train_y = train.pop('species')
test_y = test.pop('species')
train.head()

   SepalLength  SepalWidth  PetalLength  PetalWidth
0          6.4         2.8          5.6         2.2
1          5.0         2.3          3.3         1.0
2          4.9         2.5          4.5         1.7
3          4.9         3.1          1.5         0.1
4          5.7         3.8          1.7         0.3

In [8]:
train.shape

(120, 4)

In [10]:
def input_fn(features, labels, training=True, batch_size=256):
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))
    if training:
        dataset = dataset.shuffle(1000).repeat()
    return dataset.batch(batch_size)

In [11]:
my_feature_columns=[]
for key in train.keys():
    my_feature_columns.append(tf.feature_column.numeric_column(key=key))
my_feature_columns

WARNING:tensorflow:From C:\Users\Usman Mallana\AppData\Local\Temp\ipykernel_704\990311713.py:3: numeric_column (from tensorflow.python.feature_column.feature_column_v2) is deprecated and will be removed in a future version.
Instructions for updating:
Use Keras preprocessing layers instead, either directly or via the `tf.keras.utils.FeatureSpace` utility. Each of `tf.feature_column.*` has a functional equivalent in `tf.keras.layers` for feature preprocessing when training a Keras model.

[NumericColumn(key='SepalLength', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='SepalWidth', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='PetalLength', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 NumericColumn(key='PetalWidth', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

In [12]:
classifier = tf.estimator.DNNClassifier(feature_columns=my_feature_columns, hidden_units=[30, 10], n_classes=3)

WARNING:tensorflow:From C:\Users\Usman Mallana\AppData\Local\Temp\ipykernel_704\1269944313.py:1: DNNClassifierV2.__init__ (from tensorflow_estimator.python.estimator.canned.dnn) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow_estimator\python\estimator\head\head_utils.py:59: MultiClassHead.__init__ (from tensorflow_estimator.python.estimator.head.multi_class_head) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow_estimator\python\estimator\canned\dnn.py:759: Estimator.__init__ (from tensorflow_estimator.python.estimator.estimator) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py:1844: RunConfig.__init__ (from tensorflow_estimator.python.estimator.run_config) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\USMANM~1\AppData\Local\Temp\tmpl536wj9u
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\USMANM~1\\AppData\\Local\\Temp\\tmpl536wj9u', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [13]:
classifier.train(input_fn=lambda: input_fn(train, train_y, training=True), steps=5000)

WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py:385: StopAtStepHook.__init__ (from tensorflow.python.training.basic_session_run_hooks) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
INFO:tensorflow:Calling model_fn.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\keras\src\optimizers\legacy\adagrad.py:93: calling Constant.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow_estimator\python\estimator\model_fn.py:250: EstimatorSpec.__new__ (from tensorflow_estimator.python.estimator.model_fn) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
INFO:tensorflow:Done calling model_fn.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py:1416: NanTensorHook.__init__ (from tensorflow.python.training.basic_session_run_hooks) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py:1419: LoggingTensorHook.__init__ (from tensorflow.python.training.basic_session_run_hooks) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\training\basic_session_run_hooks.py:232: SecondOrStepTimer.__init__ (from tensorflow.python.training.basic_session_run_hooks) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py:1456: CheckpointSaverHook.__init__ (from tensorflow.python.training.basic_session_run_hooks) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
INFO:tensorflow:Create CheckpointSaverHook.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\training\monitored_session.py:579: StepCounterHook.__init__ (from tensorflow.python.training.basic_session_run_hooks) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\training\monitored_session.py:586: SummarySaverHook.__init__ (from tensorflow.python.training.basic_session_run_hooks) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\USMANM~1\AppData\Local\Temp\tmpl536wj9u\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\training\monitored_session.py:1455: SessionRunArgs.__new__ (from tensorflow.python.training.session_run_hook) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\training\monitored_session.py:1454: SessionRunContext.__init__ (from tensorflow.python.training.session_run_hook) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
WARNING:tensorflow:From c:\users\usman mallana\appdata\local\programs\python\python38\lib\site-packages\tensorflow\python\training\monitored_session.py:1474: SessionRunValues.__new__ (from tensorflow.python.training.session_run_hook) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.keras instead.
INFO:tensorflow:loss = 1.617101, step = 0
INFO:tensorflow:global_step/sec: 350.679
INFO:tensorflow:loss = 1.0590756, step = 100 (0.285 sec)
INFO:tensorflow:global_step/sec: 431.447
INFO:tensorflow:loss = 0.9770347, step = 200 (0.232 sec)
INFO:tensorflow:global_step/sec: 431.455
INFO:tensorflow:loss = 0.9375011, step = 300 (0.232 sec)
INFO:tensorflow:global_step/sec: 462.647
INFO:tensorflow:loss = 0.92373884, step = 400 (0.216 sec)
INFO:tensorflow:global_step/sec: 449.125
INFO:tensorflow:loss = 0.9023982, step = 500 (0.223 sec)
INFO:tensorflow:global_step/sec: 431.445
INFO:tensorflow:loss = 0.90012604, step = 600 (0.232 sec)
INFO:tensorflow:global_step/sec: 462.645
INFO:tensorflow:loss = 0.8762205, step = 700 (0.232 sec)
INFO:tensorflow:global_step/sec: 540.838
INFO:tensorflow:loss = 0.8771887, step = 800 (0.169 sec)
INFO:tensorflow:global_step/sec: 462.646
INFO:tensorflow:loss = 0.84905565, step = 900 (0.216 sec)
INFO:tensorflow:global_step/sec: 498.684
INFO:tensorflow:loss = 0.83965933, step = 1000 (0.216 sec)
INFO:tensorflow:global_step/sec: 498.691
INFO:tensorflow:loss = 0.83314526, step = 1100 (0.185 sec)
INFO:tensorflow:global_step/sec: 462.644
INFO:tensorflow:loss = 0.83111537, step = 1200 (0.216 sec)
INFO:tensorflow:global_step/sec: 498.696
INFO:tensorflow:loss = 0.8120981, step = 1300 (0.216 sec)
INFO:tensorflow:global_step/sec: 419.647
INFO:tensorflow:loss = 0.8030486, step = 1400 (0.223 sec)
INFO:tensorflow:global_step/sec: 498.696
INFO:tensorflow:loss = 0.7972222, step = 1500 (0.201 sec)
INFO:tensorflow:global_step/sec: 462.623
INFO:tensorflow:loss = 0.78941125, step = 1600 (0.216 sec)
INFO:tensorflow:global_step/sec: 498.697
INFO:tensorflow:loss = 0.79129106, step = 1700 (0.201 sec)
INFO:tensorflow:global_step/sec: 540.861
INFO:tensorflow:loss = 0.7689184, step = 1800 (0.185 sec)
INFO:tensorflow:global_step/sec: 498.694
INFO:tensorflow:loss = 0.76096326, step = 1900 (0.216 sec)
INFO:tensorflow:global_step/sec: 462.623
INFO:tensorflow:loss = 0.7567915, step = 2000 (0.201 sec)
INFO:tensorflow:global_step/sec: 540.851
INFO:tensorflow:loss = 0.7426312, step = 2100 (0.185 sec)
INFO:tensorflow:global_step/sec: 498.684
INFO:tensorflow:loss = 0.7286165, step = 2200 (0.201 sec)
INFO:tensorflow:global_step/sec: 560.562
INFO:tensorflow:loss = 0.730696, step = 2300 (0.178 sec)
INFO:tensorflow:global_step/sec: 449.123
INFO:tensorflow:loss = 0.7130505, step = 2400 (0.223 sec)
INFO:tensorflow:global_step/sec: 404.194
INFO:tensorflow:loss = 0.727519, step = 2500 (0.263 sec)
INFO:tensorflow:global_step/sec: 462.656
INFO:tensorflow:loss = 0.6945654, step = 2600 (0.201 sec)
INFO:tensorflow:global_step/sec: 498.694
INFO:tensorflow:loss = 0.7000673, step = 2700 (0.201 sec)
INFO:tensorflow:global_step/sec: 540.843
INFO:tensorflow:loss = 0.6809056, step = 2800 (0.185 sec)
INFO:tensorflow:global_step/sec: 431.447
INFO:tensorflow:loss = 0.6842032, step = 2900 (0.232 sec)
INFO:tensorflow:global_step/sec: 498.68
INFO:tensorflow:loss = 0.6699872, step = 3000 (0.201 sec)
INFO:tensorflow:global_step/sec: 498.684
INFO:tensorflow:loss = 0.6611849, step = 3100 (0.216 sec)
INFO:tensorflow:global_step/sec: 449.115
INFO:tensorflow:loss = 0.64866036, step = 3200 (0.207 sec)
INFO:tensorflow:global_step/sec: 462.633
INFO:tensorflow:loss = 0.65477335, step = 3300 (0.216 sec)
INFO:tensorflow:global_step/sec: 498.7
INFO:tensorflow:loss = 0.6596188, step = 3400 (0.201 sec)
INFO:tensorflow:global_step/sec: 462.649
INFO:tensorflow:loss = 0.63163674, step = 3500 (0.232 sec)
INFO:tensorflow:global_step/sec: 498.697
INFO:tensorflow:loss = 0.6334392, step = 3600 (0.185 sec)
INFO:tensorflow:global_step/sec: 540.82
INFO:tensorflow:loss = 0.6114017, step = 3700 (0.201 sec)
INFO:tensorflow:global_step/sec: 316.046
INFO:tensorflow:loss = 0.62029433, step = 3800 (0.301 sec)
INFO:tensorflow:global_step/sec: 498.695
INFO:tensorflow:loss = 0.6192894, step = 3900 (0.201 sec)
INFO:tensorflow:global_step/sec: 498.691
INFO:tensorflow:loss = 0.60427284, step = 4000 (0.216 sec)
INFO:tensorflow:global_step/sec: 462.642
INFO:tensorflow:loss = 0.6113974, step = 4100 (0.201 sec)
INFO:tensorflow:global_step/sec: 462.651
INFO:tensorflow:loss = 0.6035958, step = 4200 (0.216 sec)
INFO:tensorflow:global_step/sec: 540.822
INFO:tensorflow:loss = 0.5936936, step = 4300 (0.185 sec)
INFO:tensorflow:global_step/sec: 540.831
INFO:tensorflow:loss = 0.59042263, step = 4400 (0.201 sec)
INFO:tensorflow:global_step/sec: 404.2
INFO:tensorflow:loss = 0.5853696, step = 4500 (0.232 sec)
INFO:tensorflow:global_step/sec: 498.688
INFO:tensorflow:loss = 0.56205463, step = 4600 (0.201 sec)
INFO:tensorflow:global_step/sec: 462.65
INFO:tensorflow:loss = 0.5847949, step = 4700 (0.223 sec)
INFO:tensorflow:global_step/sec: 419.654
INFO:tensorflow:loss = 0.5710246, step = 4800 (0.232 sec)
INFO:tensorflow:global_step/sec: 498.698
INFO:tensorflow:loss = 0.5673479, step = 4900 (0.201 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 5000...
INFO:tensorflow:Saving checkpoints for 5000 into C:\Users\USMANM~1\AppData\Local\Temp\tmpl536wj9u\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 5000...
INFO:tensorflow:Loss for final step: 0.56896484.

In [16]:
eval_result = classifier.evaluate(input_fn=lambda: input_fn(test, test_y, training=False))
print('\nTest set accuracy: {accuracy:0.3f}\n'.format(**eval_result))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2024-06-27T17:02:33
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\USMANM~1\AppData\Local\Temp\tmpl536wj9u\model.ckpt-5000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Inference Time : 0.36330s
INFO:tensorflow:Finished evaluation at 2024-06-27-17:02:34
INFO:tensorflow:Saving dict for global step 5000: accuracy = 0.7, average_loss = 0.65101504, global_step = 5000, loss = 0.65101504
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 5000: C:\Users\USMANM~1\AppData\Local\Temp\tmpl536wj9u\model.ckpt-5000

Test set accuracy: 0.700

In [22]:
def input_fn(features, batch_size=256):
    return tf.data.Dataset.from_tensor_slices(dict(features)).batch(batch_size)

features = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']
predict = {}
print("Please type numeric values as prompted.")
for feature in features:
    valid = True
    while valid:
        val = input(feature + ": ")
        if not val.isdigit(): valid = False

    predict[feature] = [float(val)]
predictions = classifier.predict(input_fn=lambda: input_fn(predict))
for pred_dict in predictions:
    class_id = pred_dict['class_ids'][0]
    probability = pred_dict['probabilities'][class_id]
    print('Predictions is "{}" ({:.1f}%)'.format(SPECIES[class_id], 100*probability))

Please type numeric values as prompted.

SepalLength:  22.4
SepalWidth:  2.6
PetalLength:  6.5
PetalWidth:  6.3

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\USMANM~1\AppData\Local\Temp\tmpl536wj9u\model.ckpt-5000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
Predictions is "Versicolor" (83.2%)